#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To build it:
# $ docker build --file Dockerfile-cli -t rekor-cli .
#
# To run it:
# $ docker run -t rekor-cli rekor <option>

FROM golang:1.16.5 AS builder
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT

WORKDIR $APP_ROOT/src/
ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download

# Add source code
ADD ./cmd/ $APP_ROOT/src/cmd/
ADD ./pkg/ $APP_ROOT/src/pkg/

RUN go get -u -t -v github.com/sigstore/rekor/cmd/rekor-cli
RUN go build -v -o rekor $APP_ROOT/src/cmd/rekor-cli

# Multi-Stage production build
FROM golang:1.16.5 as deploy

# Retrieve the binary from the previous stage
COPY --from=builder /opt/app-root/src/rekor /usr/local/bin/rekor

# Set the binary as the entrypoint of the container
CMD ["rekor"]
